# Generated by Django 4.0.4 on 2022-05-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserT',
            fields=[
                ('ID_User', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('passwordT', models.CharField(max_length=225)),
                ('userType', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=50)),
            ],
        ),
    ]
