# Generated by Django 4.0.4 on 2022-05-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id_church', models.BigAutoField(primary_key=True, serialize=False)),
                ('namet', models.CharField(blank=True, db_column='nameT', max_length=50, null=True)),
                ('municipality', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('phone1', models.BigIntegerField(blank=True, null=True)),
                ('phone2', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usert',
            name='firstName',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='usert',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usert',
            name='passwordT',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usert',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
