# Generated by Django 4.0.4 on 2022-05-02 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_church_alter_usert_firstname_alter_usert_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id_parameter', models.BigAutoField(primary_key=True, serialize=False)),
                ('lastupdate', models.DateField(blank=True, db_column='lastUpdate', null=True)),
                ('waist', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('imc', models.IntegerField(blank=True, null=True)),
                ('clock', models.IntegerField(blank=True, null=True)),
                ('gds', models.IntegerField(blank=True, null=True)),
                ('katz', models.IntegerField(blank=True, null=True)),
                ('lwb', models.IntegerField(blank=True, null=True)),
                ('sarcf', models.IntegerField(blank=True, db_column='sarcF', null=True)),
                ('pantcirs', models.IntegerField(blank=True, db_column='pantCirs', null=True)),
                ('leftstrong', models.IntegerField(blank=True, db_column='leftStrong', null=True)),
                ('rightstrong', models.IntegerField(blank=True, db_column='rightStrong', null=True)),
                ('higheststrong', models.IntegerField(blank=True, db_column='highestStrong', null=True)),
                ('sppbbalance', models.IntegerField(blank=True, db_column='sppbBalance', null=True)),
                ('standem', models.IntegerField(blank=True, db_column='sTandem', null=True)),
                ('tandem', models.IntegerField(blank=True, null=True)),
                ('spds', models.IntegerField(blank=True, db_column='spdS', null=True)),
                ('mtss', models.IntegerField(blank=True, db_column='mtsS', null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('globalsppb', models.IntegerField(blank=True, db_column='globalSppb', null=True)),
                ('frailtysppb', models.IntegerField(blank=True, db_column='frailtySppb', null=True)),
                ('frailtycfs', models.IntegerField(blank=True, db_column='frailtyCfs', null=True)),
                ('gijon', models.IntegerField(blank=True, null=True)),
                ('ospace', models.IntegerField(blank=True, db_column='oSpace', null=True)),
                ('otime', models.IntegerField(blank=True, db_column='oTime', null=True)),
                ('calculation', models.IntegerField(blank=True, null=True)),
                ('memoryt', models.IntegerField(blank=True, db_column='memoryT', null=True)),
                ('eject', models.IntegerField(blank=True, null=True)),
                ('totalmmse', models.IntegerField(blank=True, db_column='totalMmse', null=True)),
                ('ID_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parameter')),
            ],
        ),
    ]
