# Generated by Django 4.0.4 on 2022-05-02 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='usert',
            name='id_church',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.usert'),
            preserve_default=False,
        ),
    ]
