# Generated by Django 4.0.4 on 2022-05-02 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usert_id_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='ID_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usert'),
        ),
        migrations.AlterField(
            model_name='usert',
            name='id_church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.church'),
        ),
    ]
