# Generated by Django 4.0.4 on 2022-05-04 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_parameter_id_user_alter_usert_id_church'),
    ]

    operations = [
        migrations.AddField(
            model_name='usert',
            name='username',
            field=models.CharField(default='text', max_length=20, verbose_name='Username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='church',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='church',
            name='cp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='church',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='church',
            name='municipality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='church',
            name='namet',
            field=models.CharField(blank=True, db_column='nameT', max_length=50, null=True, verbose_name='Nombre de la iglesia'),
        ),
        migrations.AlterField(
            model_name='church',
            name='phone1',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='church',
            name='phone2',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Teléfono alterno'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='waist',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cintura'),
        ),
        migrations.AlterField(
            model_name='usert',
            name='firstName',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usert',
            name='gender',
            field=models.CharField(max_length=20, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='usert',
            name='id_church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.church', verbose_name='Iglesia'),
        ),
        migrations.AlterField(
            model_name='usert',
            name='lastName',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usert',
            name='mail',
            field=models.CharField(max_length=50, verbose_name='Correro electrónico'),
        ),
        migrations.AlterField(
            model_name='usert',
            name='passwordT',
            field=models.CharField(max_length=255, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usert',
            name='phone',
            field=models.BigIntegerField(verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usert',
            name='userType',
            field=models.CharField(max_length=20, verbose_name='Tipo de usuario'),
        ),
    ]
