# Generated by Django 4.0.4 on 2022-05-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usert_username_alter_church_address_alter_church_cp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usert',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
