# Generated by Django 4.0.4 on 2022-05-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_usert_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='phone1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='church',
            name='phone2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono alterno'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='calculation',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='clock',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='eject',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='frailtycfs',
            field=models.DecimalField(blank=True, db_column='frailtyCfs', decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='frailtysppb',
            field=models.DecimalField(blank=True, db_column='frailtySppb', decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='gds',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='gijon',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='globalsppb',
            field=models.DecimalField(blank=True, db_column='globalSppb', decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='higheststrong',
            field=models.DecimalField(blank=True, db_column='highestStrong', decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='katz',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='leftstrong',
            field=models.DecimalField(blank=True, db_column='leftStrong', decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='lwb',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='memoryt',
            field=models.DecimalField(blank=True, db_column='memoryT', decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='mtss',
            field=models.DecimalField(blank=True, db_column='mtsS', decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='ospace',
            field=models.DecimalField(blank=True, db_column='oSpace', decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='otime',
            field=models.DecimalField(blank=True, db_column='oTime', decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='pantcirs',
            field=models.DecimalField(blank=True, db_column='pantCirs', decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='rightstrong',
            field=models.DecimalField(blank=True, db_column='rightStrong', decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='sarcf',
            field=models.DecimalField(blank=True, db_column='sarcF', decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='spds',
            field=models.DecimalField(blank=True, db_column='spdS', decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='speed',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='sppbbalance',
            field=models.DecimalField(blank=True, db_column='sppbBalance', decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='standem',
            field=models.DecimalField(blank=True, db_column='sTandem', decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='tandem',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='totalmmse',
            field=models.DecimalField(blank=True, db_column='totalMmse', decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='waist',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Cintura'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='usert',
            name='isAdmin',
            field=models.BooleanField(default=False, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='usert',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Teléfono'),
        ),
    ]
