# Generated by Django 4.0.4 on 2022-05-05 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_alter_church_phone1_alter_church_phone2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20, verbose_name='Género')),
                ('phone', models.CharField(max_length=255, verbose_name='Teléfono')),
                ('mail', models.CharField(max_length=50, verbose_name='Correro electrónico')),
                ('isAdmin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('id_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.church', verbose_name='Iglesia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
