# Generated by Django 4.0.4 on 2022-05-05 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_extended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='ID_User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prueba', to=settings.AUTH_USER_MODEL),
        ),
    ]
